export const banks = [
  {
    id: 1,
    code: "ACB",
    name: "Ngân hàng TMCP Á Châu (ACB)",
    swiftCode: "ASCBVNVX",
  },
  {
    id: 2,
    code: "VietcomBank",
    name: "Ngân hàng TMCP Ngoại Thương Việt Nam (VietcomBank)",
    swiftCode: "BFTVVNVX",
  },
  {
    id: 3,
    code: "VietinBank",
    name: "Ngân hàng TMCP Công Thương Việt Nam (VietinBank)",
    swiftCode: "ICBVVNVX",
  },
  {
    id: 4,
    code: "Techcombank",
    name: "Ngân hàng TMCP Kỹ Thương Việt Nam (Techcombank)",
    swiftCode: "VTCBVNVX",
  },
  {
    id: 5,
    code: "BIDV",
    name: "Ngân hàng TMCP Đầu Tư Và Phát Triển Việt Nam (BIDV)",
    swiftCode: "BIDVVNVX",
  },
  {
    id: 6,
    code: "MaritimeBank",
    name: "Ngân hàng TMCP Hàng Hải Việt Nam (MaritimeBank)",
    swiftCode: "MCOBVNVX",
  },
  {
    id: 7,
    code: "VPBank",
    name: "Ngân hàng Việt Nam Thịnh Vượng (VPBank)",
    swiftCode: "VPBKVNVX",
  },
  {
    id: 8,
    code: "Agribank",
    name: "Ngân hàng Nông nghiệp và Phát triển Việt Nam (Agribank)",
    swiftCode: "VBAAVNVX",
  },
  {
    id: 9,
    code: "Eximbank",
    name: "Ngân hàng TMCP Xuất nhập khẩu Việt Nam (Eximbank)",
    swiftCode: "EBVIVNVX",
  },
  {
    id: 10,
    code: "Sacombank",
    name: "Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)",
    swiftCode: "SGTTVNVX",
  },
  {
    id: 11,
    code: "DongA Bank",
    name: "Ngân hàng TMCP Đông Á (DongA Bank)",
    swiftCode: "EACBVNVX",
  },
  {
    id: 12,
    code: "NASB",
    name: "Ngân hàng TMCP Bắc Á (NASB)",
    swiftCode: "NASCVNVX",
  },
  {
    id: 13,
    code: "ANZ Bank",
    name: "Ngân hàng TNHH một thành viên ANZ Việt Nam (ANZ Bank)",
    swiftCode: "ANZBVNVX",
  },
  {
    id: 14,
    code: "Phuong Nam Bank",
    name: "Ngân hàng TMCP Phương Nam (Phuong Nam Bank)",
    swiftCode: "PNBKVNVX",
  },
  {
    id: 15,
    code: "VIB",
    name: "Ngân hàng TMCP Quốc tế Việt Nam (VIB)",
    swiftCode: "VNIBVNVX",
  },
  {
    id: 16,
    code: "VietABank",
    name: "Ngân hàng TMCP Việt Á (VietABank)",
    swiftCode: "VNACVNVX",
  },
  {
    id: 17,
    code: "TPBank",
    name: "Ngân hàng TMCP Tiên Phong (TPBank)",
    swiftCode: "TPBVVNVX",
  },
  {
    id: 18,
    code: "MBBank",
    name: "Ngân hàng thương mại cổ phần Quân đội (MBBank)",
    swiftCode: "MSCBVNVX",
  },
  {
    id: 19,
    code: "OceanBank",
    name: "Ngân hàng TM TNHH 1 thành viên Đại Dương (OceanBank)",
    swiftCode: "OJBAVNVX",
  },
  {
    id: 20,
    code: "PG Bank",
    name: "Ngân hàng TMCP Xăng dầu Petrolimex (PG Bank)",
    swiftCode: "PGBLVNVX",
  },
  {
    id: 21,
    code: "LienVietPostBank",
    name: "Ngân hàng TMCP Bưu Điện Liên Việt (LienVietPostBank)",
    swiftCode: "LVBKVNVX",
  },
  {
    id: 22,
    code: "HSBC Bank",
    name: "Ngân hàng TNHH một thành viên HSBC (Việt Nam) (HSBC Bank)",
    swiftCode: "HSBCVNVX",
  },
  {
    id: 23,
    code: "MHB Bank",
    name: "Ngân hàng Phát triển nhà đồng bằng sông Cửu Long (MHB Bank)",
    swiftCode: "MHBBVNVX",
  },
  {
    id: 24,
    code: "SeABank",
    name: "Ngân hàng TMCP Đông Nam Á (SeABank)",
    swiftCode: "SEAVVNVX",
  },
  {
    id: 25,
    code: "ABBank",
    name: "Ngân hàng TMCP An Bình (ABBank)",
    swiftCode: "ABBKVNVX",
  },
  {
    id: 26,
    code: "CITIBANK N.A.",
    name: "Ngân hàng Citibank Việt Nam (CITIBANK N.A.)",
    swiftCode: "CITIVNVX",
  },
  {
    id: 27,
    code: "HDBank",
    name: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh (HDBank)",
    swiftCode: "HDBCVNVX",
  },
  {
    id: 28,
    code: "GBBank",
    name: "Ngân hàng Dầu khí Toàn cầu (GBBank)",
    swiftCode: "GBNKVNVX",
  },
  {
    id: 29,
    code: "OCB",
    name: "Ngân hàng TMCP Phương Đông (OCB)",
    swiftCode: "ORCOVNVX",
  },
  {
    id: 30,
    code: "SHB",
    name: "Ngân Hàng Thương Mại cổ phần Sài Gòn – Hà Nội (SHB)",
    swiftCode: "SHBAVNVX",
  },
  {
    id: 31,
    code: "Nam A Bank",
    name: "Ngân hàng Thương Mại cổ phần Nam Á (Nam A Bank)",
    swiftCode: "NAMAVNVX",
  },
  {
    id: 32,
    code: "Saigon Bank",
    name: "Ngân Hàng TMCP Sài Gòn Công Thương (Saigon Bank)",
    swiftCode: "SBITVNVX",
  },
  {
    id: 33,
    code: "SCB",
    name: "Ngân hàng TMCP Sài Gòn (SCB)",
    swiftCode: "SACLVNVX",
  },
  {
    id: 34,
    code: "VNCB",
    name: "Ngân hàng thương mại TNHH MTV Xây dựng Việt Nam (VNCB)",
    swiftCode: "GTBAVNVX",
  },
  {
    id: 35,
    code: "Kienlongbank",
    name: "Ngân hàng Thương mại Cổ phần Kiên Long (Kienlongbank)",
    swiftCode: "KLBKVNVX",
  },
  {
    id: 36,
    code: "Shinhan Bank",
    name: "Ngân hàng Shinhan Việt Nam (Shinhan Bank)",
    swiftCode: "SHBKVNVX",
  },
  {
    id: 37,
    code: "Baoviet Bank",
    name: "Ngân hàng Bảo Việt (Baoviet Bank)",
    swiftCode: "BVBVVNVX",
  },
  {
    id: 38,
    code: "Vietbank",
    name: "Ngân hàng Việt Nam Thương Tín (Vietbank)",
    swiftCode: "VNTTVNVX",
  },
  {
    id: 39,
    code: "PVcomBank",
    name: "Ngân hàng TMCP Đại Chúng Việt Nam (PVcomBank)",
    swiftCode: "WBVNVNVX",
  },
  {
    id: 40,
    code: "Eximbank",
    name: "Ngân hàng Xuất Nhập Khẩu (Eximbank)",
    swiftCode: "EBVIVNVX",
  },
];
